apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
        image: fabricioveronez/pagina-exemplo:blue
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webpage
spec:
  selector:
    app: webpage
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webpages
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
        image: fabricioveronez/pagina-exemplo:blue
        ports:
        - containerPort: 80 
  minReadySeconds: 30
  strategy:
    blueGreen: 
      activeService: webpage-active
      previewService: webpage-preview
      autoPromotionEnabled: false
      autoPromotionSeconds: 30
      scaleDownDelaySeconds: 60